Repository Joinble/joinble-ui, pull requests merged in 2020-11, with the labels that each got.

#10 Feature/button
  .eslintignore
  .eslintrc
  example/src/App.tsx
  example/tsconfig.json
  example/yarn.lock
  package.json
  src/.eslintrc
  src/Theme.ts
  src/components/button/Button.test.tsx
  src/components/button/Button.tsx
  src/components/icons/index.ts
  src/components/icons/searchIcon.tsx
  src/index.test.tsx
  src/index.ts
  src/index.tsx
  src/styles.module.css
  src/typings.d.ts
  yarn.lock
Labels: enhancement

#13 feat(components): #12 create Checkbox component
  example/src/App.tsx
  src/components/button/Button.tsx
  src/components/button/ButtonStyles.tsx
  src/components/checkbox/Checkbox.test.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/checkbox/CheckboxStyles.tsx
  src/components/index.ts
  src/components/input/Input.tsx
  src/components/input/InputStyle.tsx
Labels: UI, enhancement

#18 fix(components): #17 component input does not have the property name …
  src/components/input/Input.tsx
  src/components/input/InputStyle.tsx
Labels: bug

#28 fix(components): #27 add onClick prop Buttons
  example/src/App.tsx
  src/components/button/Button.tsx
  src/components/button/ButtonIcon.tsx
  src/components/button/ButtonSocialMedia.tsx
  src/components/button/ButtonStyles.tsx
  src/components/input/InputStyle.tsx
Labels: bug

#38 fix(components): #37 add testId label on components for cypress
  .releaserc
  package.json
  src/components/checkbox/Checkbox.tsx
  src/components/checkbox/CheckboxStyles.tsx
  src/components/colorPicker/ColorPicker.tsx
  src/components/input/Input.tsx
  yarn.lock
Labels: bug

#42 fix(components): #41 onClick prop in Button is an optional prop
  src/components/button/Button.tsx
Labels: bug

#65 fix(components): #64 checkbox component is not working properly
  src/components/checkbox/Checkbox.tsx
  src/components/checkbox/CheckboxStyles.tsx
Labels: bug
